name: yordam-frontend

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "51851:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
